name: Deploy Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: 安装依赖
        run: pnpm i --no-frozen-lockfile --shamefully-hoist

      - name: 构建 & 部署
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          packageManager: pnpm

      - name: 打印部署链接
        env:
          DEPLOYMENT_URL: ${{ steps.deploy.outputs.deployment-url }}
        run: echo $DEPLOYMENT_URL
